version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            - MYSQL_HOST=db
            - MYSQL_USER=italiaonline
            - MYSQL_PASSWORD=password
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    
    db:
        image: "mysql:8"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=italiaonline
            - MYSQL_USER=italiaonline
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
            - .:/data:z
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        command: "--character-set-server=utf8 --collation-server=utf8_general_ci --secure-file-priv=data/public"
